In [ ]:
import pandas as pd
import json
import os
import zipfile
import glob
import time

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Reading the CSV form response files and extracting the file locations

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Research stuff/Final Year Design Project/Survey and collected data/Total MindSeer_Data_Collection (Responses) - Form Responses 1.csv')
df.head()

            Timestamp  ... Please attach the file in the following file upload option.
0  11/3/2020 11:23:00  ...  https://drive.google.com/open?id=1-3cRHtc5pU31...
1  11/3/2020 12:55:33  ...  https://drive.google.com/open?id=1BesX6mVyvInx...
2  11/3/2020 14:03:20  ...  https://drive.google.com/open?id=1mXmC2VI9x08E...
3  11/3/2020 14:32:38  ...  https://drive.google.com/open?id=1zQfz3OiA9Tg9...
4  11/3/2020 16:12:37  ...  https://drive.google.com/open?id=1N-Hp4AMFBm4A...

[5 rows x 25 columns]

In [ ]:
df.tail()

              Timestamp  ... Please attach the file in the following file upload option.
99    1/8/2021 17:05:52  ...  https://drive.google.com/open?id=1YFVDBiMn5VvE...
100   1/10/2021 0:07:38  ...  https://drive.google.com/open?id=1GAfJflMTtfv-...
101  1/18/2021 23:15:06  ...  https://drive.google.com/open?id=1vZ0PzUU_dFlS...
102  1/19/2021 20:29:15  ...  https://drive.google.com/open?id=17ztrixwsgsCh...
103   1/20/2021 2:53:08  ...  https://drive.google.com/open?id=1g5vXihaUn5E9...

[5 rows x 25 columns]

In [ ]:
file_links = df['Please attach the file in the following file upload option.']
file_links.shape

(104,)

In [ ]:
file_links.head

<bound method NDFrame.head of 0      https://drive.google.com/open?id=1-3cRHtc5pU31...
1      https://drive.google.com/open?id=1BesX6mVyvInx...
2      https://drive.google.com/open?id=1mXmC2VI9x08E...
3      https://drive.google.com/open?id=1zQfz3OiA9Tg9...
4      https://drive.google.com/open?id=1N-Hp4AMFBm4A...
                             ...
99     https://drive.google.com/open?id=1YFVDBiMn5VvE...
100    https://drive.google.com/open?id=1GAfJflMTtfv-...
101    https://drive.google.com/open?id=1vZ0PzUU_dFlS...
102    https://drive.google.com/open?id=17ztrixwsgsCh...
103    https://drive.google.com/open?id=1g5vXihaUn5E9...
Name: Please attach the file in the following file upload option., Length: 104, dtype: object>

In [ ]:
file_links.shape[0]

104

Downloading and extracting the files

In [ ]:
#making a directory to download data
!mkdir /content/mindseer_data

In [ ]:
#method 1:

def download_files(start, end):
    time.sleep(100)
    for i in range(start, end):
        path = '/content/mindseer_data/'
        participant_id = i
        url = file_links[i]
        file_id_index = url.find('id')
        file_id = url[file_id_index + 3 : ]
        data_zip = path + f'{participant_id}.zip'
        command = 'gdown --id ' + file_id + " -O " + data_zip
        m = os.system(command)
        print(m, participant_id)

        with zipfile.ZipFile(data_zip, "r") as zip_ref:
            path = path + f"{participant_id}/"
            zip_ref.extractall(path)
            zip_ref.close()
        
        #time.sleep(100)

In [ ]:
#method 2:
import gdown

def download_files_2(start, end):
    for i in range(start, end):
        path = '/content/mindseer_data/'
        participant_id = i
        url = file_links[i]
        file_id_index = url.find('id')
        file_id = url[file_id_index + 3 : ]
        url = f"https://drive.google.com/uc?id={file_id}"
        data_zip = path + f'{participant_id}.zip'
        gdown.download(url, data_zip, quiet=False)

        with zipfile.ZipFile(data_zip, "r") as zip_ref:
            path = path + f"{participant_id}/"
            zip_ref.extractall(path)
            zip_ref.close()

In [ ]:
download_files(0, 20)

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19

In [ ]:
download_files(20, 40)

0 20
0 21
0 22
0 23
0 24
0 25
0 26
0 27
0 28
0 29
0 30
0 31
0 32
0 33
0 34
0 35
0 36
0 37
0 38
0 39

In [ ]:
download_files_2(40, 60)

Downloading...
From: https://drive.google.com/uc?id=1ixrB3Q4LLWgKsjvc_Hd5Im-sVQZes1kY
To: /content/mindseer_data/40.zip
100%|██████████| 1.73k/1.73k [00:00<00:00, 1.79MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_p-LpSufuPRo6x-9ExvVC8lBC3qg_Lr9
To: /content/mindseer_data/41.zip
7.72MB [00:00, 19.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=17xBb4f-FauWSjsBsiCqeXS_wMHFEl_gw
To: /content/mindseer_data/42.zip
100%|██████████| 43.1k/43.1k [00:00<00:00, 6.98MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Qq4UlmFBjIUGKZggStKNYHGFmMZhH-zt
To: /content/mindseer_data/43.zip
100%|██████████| 5.39k/5.39k [00:00<00:00, 1.69MB/s]
Downloading...
From: https://drive.google.com/uc?id=1LugttDjHRsnQg6s7Z5g2NIhGO1yx7Z8I
To: /content/mindseer_data/44.zip
100%|██████████| 2.13k/2.13k [00:00<00:00, 2.33MB/s]
Downloading...
From: https://drive.google.com/uc?id=1QhrwRSvzO3g9PjdbglfgG3sb-RZg-pEe
To: /content/mindseer_data/45.zip
100%|██████████| 103k/103k [00:00<00:00, 5.54MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IuxEjN2ZjN1twRTFdG8vxO0i13wU7mNz
To: /content/mindseer_data/46.zip
100%|██████████| 143k/143k [00:00<00:00, 6.68MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Xn3ESP-YzK580SOfY6n2bV3bB78tPAsf
To: /content/mindseer_data/47.zip
100%|██████████| 107k/107k [00:00<00:00, 5.41MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IVSJBEj0YsUadUgOhAT5sBkTaajlZcxM
To: /content/mindseer_data/48.zip
100%|██████████| 67.4k/67.4k [00:00<00:00, 6.19MB/s]
Downloading...
From: https://drive.google.com/uc?id=166M-AW3hIYUv5Kb5enfAsi0EPCqfg18w
To: /content/mindseer_data/49.zip
100%|██████████| 150k/150k [00:00<00:00, 6.25MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AWF7fsITHrc250P9AZR2cvyPS23g5j3S
To: /content/mindseer_data/50.zip
100%|██████████| 337k/337k [00:00<00:00, 10.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JLsU-mQrMzCp-X4HULDznJSWMz8apg6d
To: /content/mindseer_data/51.zip
100%|██████████| 549k/549k [00:00<00:00, 14.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Kcm-AX0iyMmpEWr1MhgkhQyOARcq5fK9
To: /content/mindseer_data/52.zip
100%|██████████| 461k/461k [00:00<00:00, 12.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xvS3ZIUfg0S-9wQctcYst3OjdrE3WFCj
To: /content/mindseer_data/53.zip
32.8MB [00:00, 54.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1wmEwg2HkyHdBpjU-Z0sj-aqxLjtr508I
To: /content/mindseer_data/54.zip
100%|██████████| 10.9k/10.9k [00:00<00:00, 3.88MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZXqGWjPFxvjB_-vAXHRPsvVqKAOAq3ST
To: /content/mindseer_data/55.zip
100%|██████████| 33.4k/33.4k [00:00<00:00, 7.79MB/s]
Downloading...
From: https://drive.google.com/uc?id=1YwZ9uK9aLzfQOiUVh0CgqsxQho8IwvDJ
To: /content/mindseer_data/56.zip
100%|██████████| 2.07k/2.07k [00:00<00:00, 946kB/s]
Downloading...
From: https://drive.google.com/uc?id=1KyTWXcuuTJEIfi8s3GSfBeZvq_CFSmAr
To: /content/mindseer_data/57.zip
100%|██████████| 283k/283k [00:00<00:00, 9.20MB/s]
Downloading...
From: https://drive.google.com/uc?id=1b0qjQs4FAwY63BrlfjRE64dR3LAEUUT_
To: /content/mindseer_data/58.zip
100%|██████████| 1.90M/1.90M [00:00<00:00, 36.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1VpJgzDEVpd9KdX2YkoibqPu_fxNyYgGq
To: /content/mindseer_data/59.zip
30.8MB [00:00, 68.0MB/s]

In [ ]:
download_files(60, 80)

0 60
0 61
0 62
0 63
0 64
0 65
0 66
0 67
0 68
0 69
0 70
0 71
0 72
0 73
0 74
0 75
0 76
0 77
0 78
0 79

In [ ]:
download_files(80, 104)

0 80
0 81
0 82
0 83
0 84
0 85
0 86
0 87
0 88
0 89
0 90
0 91
0 92
0 93
0 94
0 95
0 96
0 97
0 98
0 99
0 100
0 101
0 102
0 103

In [ ]:
count = 0

for name in glob.glob('/content/mindseer_data/*.zip', recursive= True): 
    count += 1

print(count)

0

In [ ]:
#downloading the data files

%cd /content/
!zip -r /content/mindseer_data.zip /content/mindseer_data/

Streaming output truncated to the last 5000 lines.
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81210690_2532551530289648_6603792575885213696_o_2532551526956315.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80346432_2532583896953078_8228163174466060288_o_2532583893619745.jpg (deflated 5%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81347315_2542779875933480_4887788055475257344_o_2542779872600147.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79946720_2532615180283283_6694702855854489600_o_2532615173616617.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80773713_2532587433619391_3814395133143547904_n_2532587430286058.jpg (deflated 6%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80549892_2532552673622867_568036255556698112_n_2532552670289534.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80564377_2532551756956292_3166062819015655424_o_2532551753622959.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81028726_2542778159266985_2958497378996322304_o_2542778152600319.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79998475_2532545820290219_7635639291720237056_n_2532545816956886.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79920277_2532582653619869_5420897624095981568_n_2532582650286536.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79519898_2532632963614838_1326506164107608064_o_2532632960281505.jpg (deflated 4%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80679262_2532599876951480_8221101956173660160_n_2532599873618147.jpg (deflated 6%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80799173_2532549436956524_7838681083204861952_n_2532549433623191.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80128618_2532559973622137_8876946799462449152_n_2532559970288804.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80027581_2532590153619119_3551302517675524096_o_2532590150285786.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81253151_2532553390289462_5543904306337415168_o_2532553386956129.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79241688_2510790952465706_6064622761165193216_o_2510790949132373.jpg (deflated 8%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79981986_2532577233620411_3706934372792795136_o_2532577226953745.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79804554_2532549836956484_5907127031975378944_o_2532549833623151.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81328271_2532606016950866_5104292525028409344_o_2532606013617533.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81113440_2541465399398261_759367376327147520_n_2541465396064928.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79795022_2532567473621387_588168373590818816_n_2532567470288054.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80009511_2532570490287752_2772332051615973376_n_2532570486954419.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79694824_2532584200286381_4216912252579610624_n_2532584196953048.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79739669_2532620870282714_3844775266484224000_o_2532620863616048.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/78587322_2532637096947758_6297841001461448704_n_2532637093614425.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80769026_2541466626064805_3338399094732226560_o_2541466622731472.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80036246_2532565510288250_5153126152860073984_n_2532565506954917.jpg (deflated 6%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80403535_2532617333616401_3836262791627407360_o_2532617330283068.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80415738_2532575826953885_1227380350435459072_n_2532575823620552.jpg (deflated 6%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80604660_2532636126947855_1964494882726739968_n_2532636123614522.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81015882_2542780092600125_2218226741527183360_n_2542780089266792.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80466044_2532617936949674_4680928480446119936_o_2532617933616341.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79791506_2532614520283349_5992600334319484928_n_2532614516950016.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80390220_2532628506948617_5887286714019348480_n_2532628503615284.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80051634_2532589996952468_4835401330048630784_o_2532589993619135.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80761112_2532603943617740_330662754660646912_o_2532603936951074.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79861134_2532553516956116_7117112172156551168_n_2532553513622783.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80020104_2532587963619338_4088013729906556928_n_2532587960286005.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81702248_2541475416063926_6562268505649971200_o_2541475412730593.jpg (deflated 11%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80558798_2532561893621945_5680925840527851520_n_2532561890288612.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79799411_2532612156950252_240623756052004864_n_2532612153616919.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79735286_2532597566951711_244708484698865664_o_2532597560285045.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80257372_2532627766948691_6361201059091709952_n_2532627763615358.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79902146_2532600660284735_4429346312906866688_o_2532600653618069.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80964529_2541466349398166_4651167552540508160_n_2541466339398167.jpg (deflated 4%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80398188_2532587050286096_7245889237449441280_o_2532587043619430.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80279283_2532575200287281_753213959502299136_o_2532575193620615.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80388906_2532618700282931_8754751475197935616_o_2532618696949598.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81297580_2541467756064692_6194903331299655680_n_2541467752731359.jpg (deflated 4%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81452768_2542774812600653_3599236336973774848_o_2542774809267320.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81038616_2541465046064963_5835553416327200768_o_2541465039398297.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80043170_2532589946952473_8638936294786859008_n_2532589943619140.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81082963_2542778845933583_6331542785199439872_n_2542778842600250.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80675257_2542777225933745_2272752334897414144_o_2542777215933746.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79895511_2532600393618095_5528258474917494784_o_2532600390284762.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79902394_2532566703621464_3130874864924098560_o_2532566696954798.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80268817_2532559090288892_3396197345807826944_n_2532559086955559.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80458566_2532618526949615_203228549547556864_n_2532618523616282.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80266056_2532618453616289_9093343881948299264_n_2532618450282956.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79921864_2532564956954972_6867136558609203200_n_2532564953621639.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79926536_2532636660281135_7638383694218002432_o_2532636653614469.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80058004_2532567540288047_5461778900935770112_n_2532567536954714.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80207045_2532564166955051_3381036459145297920_o_2532564160288385.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80757757_2532636953614439_8938112910488502272_n_2532636946947773.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80050663_2532628906948577_8040895801427230720_o_2532628903615244.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80518536_2532601480284653_7519548279919476736_o_2532601476951320.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79943965_2532563990288402_4372539340283183104_o_2532563983621736.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79530335_2531748273703307_2192410234276806656_n_2531748270369974.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80355724_2532560793622055_4466862435625598976_n_2532560790288722.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80008880_2532628673615267_8624404625128161280_n_2532628670281934.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80886313_2542776849267116_3736788909510623232_n_2542776845933783.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79485490_2542776842600450_159183028566884352_n_2542776839267117.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79885058_2532621943615940_3151782198785343488_n_2532621940282607.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80717079_2532594363618698_1266553810839404544_o_2532594360285365.jpg (deflated 4%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81796143_2541474626064005_4058697232331833344_n_2541474622730672.jpg (deflated 4%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80450388_2532564316955036_7218351337371598848_o_2532564310288370.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80800769_2532584703619664_2222771267897917440_n_2532584700286331.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80966105_2532585113619623_1134437661876944896_o_2532585110286290.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/82053696_2541474132730721_5407466033000742912_n_2541474129397388.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80698588_2532563520288449_5494918112677462016_n_2532563516955116.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81365066_2541469109397890_2885718784503447552_n_2541469106064557.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81898874_2543305025880965_4651241073790681088_o_2543305022547632.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80260332_2532581103620024_9057730597245419520_n_2532581096953358.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80557674_2532562683621866_1238791159417929728_n_2532562680288533.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79805616_2532596756951792_6927339351420436480_o_2532596750285126.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80114211_2532545526956915_2740435489877131264_n_2532545523623582.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79818305_2532553886956079_984035483493335040_o_2532553883622746.jpg (deflated 5%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80838714_2541472719397529_425835291454996480_o_2541472706064197.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80236279_2532575850287216_1740682148362321920_o_2532575843620550.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81379707_2541462912731843_3386979607256236032_o_2541462909398510.jpg (deflated 7%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79762077_2532588026952665_4469267497052274688_n_2532588023619332.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80255363_2532608876950580_337107262893981696_n_2532608873617247.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80840545_2541474169397384_2414665415931199488_o_2541474159397385.jpg (deflated 7%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79989120_2532563053621829_1826092228787830784_o_2532563046955163.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80782341_2541463252731809_7600842407285882880_o_2541463246065143.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/78473764_2532627856948682_8906331428103389184_n_2532627853615349.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80796313_2541473002730834_2921437901495468032_o_2541472996064168.jpg (deflated 7%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81149918_2542777075933760_2521678206898012160_n_2542777072600427.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80018388_2532564656955002_7671597694225219584_n_2532564653621669.jpg (deflated 6%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/82136033_2542779132600221_786611912958803968_o_2542779125933555.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80979431_2532560753622059_3311690192061988864_o_2532560746955393.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80467806_2532582806953187_29137268589461504_o_2532582803619854.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80766422_2541466932731441_330554521484787712_o_2541466929398108.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79999826_2532587743619360_7303970771682983936_o_2532587736952694.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80518550_2532616726949795_8608371825744805888_o_2532616720283129.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81662650_2532629546948513_6685046622616813568_n_2532629543615180.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80298273_2532631736948294_3980751620383178752_o_2532631733614961.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80430808_2541465886064879_1238354176560332800_o_2541465876064880.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80226377_2532609630283838_9008391082395828224_n_2532609626950505.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80579767_2532564430288358_5433302649287999488_n_2532564426955025.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80012997_2532558550288946_5698142109559685120_o_2532558546955613.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81024285_2532594863618648_159508320799948800_o_2532594860285315.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79817666_2532622156949252_2828820698443546624_n_2532622153615919.jpg (deflated 6%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79532791_2532621880282613_5198256118723248128_n_2532621876949280.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81031488_2532557593622375_7966039757023084544_o_2532557586955709.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79993344_2532599953618139_1545087215988637696_o_2532599946951473.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81205187_2541465462731588_7539273449802301440_n_2541465456064922.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80378582_2532597766951691_3914774888287567872_n_2532597763618358.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80445301_2532633290281472_6730091668386611200_o_2532633286948139.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80877610_2532612066950261_6810666281356754944_o_2532612060283595.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80673052_2532558883622246_9129953259761434624_n_2532558880288913.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80327540_2532613900283411_9124401512020180992_n_2532613896950078.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80004331_2532564883621646_2589709419419795456_o_2532564876954980.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80389006_2541471889397612_1880377948234579968_n_2541471879397613.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81074715_2532590796952388_3919498506204610560_n_2532590793619055.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79896796_2532557983622336_6414660431125676032_o_2532557980289003.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79927631_2532629370281864_4722245765185929216_n_2532629366948531.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80116894_2532554656956002_2345053251717562368_o_2532554650289336.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80373059_2532615526949915_4812071514373357568_o_2532615520283249.jpg (deflated 2%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79645965_2532616160283185_9184654989740474368_o_2532616156949852.jpg (deflated 3%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/81272494_2542781325933335_4386428976755638272_o_2542781319266669.jpg (deflated 0%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80335504_2532621773615957_2826629925820170240_o_2532621766949291.jpg (deflated 1%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/80795452_2541463322731802_393502846370185216_o_2541463316065136.jpg (deflated 7%)
  adding: content/mindseer_data/82/photos_and_videos/your_posts/79769729_2532629736948494_8118534306034352128_o_2532629733615161.jpg (deflated 2%)

In [ ]:
from google.colab import files
files.download("/content/mindseer_data.zip")